import type { Funcionario } from "@/types/funcionario.ts"

export const initialFuncionarios: readonly Funcionario[] = [
  // Funcionarios da fiscalização fis-1 (Limpeza Total - Jan/2025)
  {
    id: "func-1",
    fiscalizacaoId: "fis-1",
    nome: "José Almeida",
    cargo: "Auxiliar de Limpeza",
    salario: 1800,
    recebeuVT: true,
    recebeuFGTS: true,
    recebeuINSS: true,
    recebeuCestaBasica: true,
    substituto: false,
    horasTrabalhadas: 176,
    riscoInconformidade: "baixo",
  },
  {
    id: "func-2",
    fiscalizacaoId: "fis-1",
    nome: "Fernanda Costa",
    cargo: "Auxiliar de Limpeza",
    salario: 1800,
    recebeuVT: true,
    recebeuFGTS: true,
    recebeuINSS: true,
    recebeuCestaBasica: true,
    substituto: false,
    horasTrabalhadas: 168,
    riscoInconformidade: "baixo",
  },
  {
    id: "func-3",
    fiscalizacaoId: "fis-1",
    nome: "Ricardo Lima",
    cargo: "Encarregado",
    salario: 2500,
    recebeuVT: true,
    recebeuFGTS: true,
    recebeuINSS: true,
    recebeuCestaBasica: true,
    substituto: false,
    horasTrabalhadas: 176,
    riscoInconformidade: "baixo",
  },
  // Funcionarios da fiscalização fis-2 (Segurança Patrimonial - Jan/2025)
  {
    id: "func-4",
    fiscalizacaoId: "fis-2",
    nome: "Marcos Souza",
    cargo: "Vigilante",
    salario: 2200,
    recebeuVT: true,
    recebeuFGTS: false,
    recebeuINSS: true,
    recebeuCestaBasica: true,
    substituto: false,
    horasTrabalhadas: 180,
    riscoInconformidade: "alto",
  },
  {
    id: "func-5",
    fiscalizacaoId: "fis-2",
    nome: "Paulo Mendes",
    cargo: "Vigilante",
    salario: 2200,
    recebeuVT: false,
    recebeuFGTS: true,
    recebeuINSS: true,
    recebeuCestaBasica: false,
    substituto: false,
    horasTrabalhadas: 176,
    riscoInconformidade: "alto",
  },
  {
    id: "func-6",
    fiscalizacaoId: "fis-2",
    nome: "André Rocha",
    cargo: "Supervisor",
    salario: 3000,
    recebeuVT: true,
    recebeuFGTS: true,
    recebeuINSS: true,
    recebeuCestaBasica: true,
    substituto: false,
    horasTrabalhadas: 176,
    riscoInconformidade: "baixo",
  },
  // Funcionarios da fiscalização fis-3 (Limpeza Total - Fev/2025)
  {
    id: "func-7",
    fiscalizacaoId: "fis-3",
    nome: "José Almeida",
    cargo: "Auxiliar de Limpeza",
    salario: 1800,
    recebeuVT: true,
    recebeuFGTS: true,
    recebeuINSS: true,
    recebeuCestaBasica: true,
    substituto: false,
    horasTrabalhadas: 160,
    riscoInconformidade: "baixo",
  },
  {
    id: "func-8",
    fiscalizacaoId: "fis-3",
    nome: "Fernanda Costa",
    cargo: "Auxiliar de Limpeza",
    salario: 1800,
    recebeuVT: true,
    recebeuFGTS: true,
    recebeuINSS: false,
    recebeuCestaBasica: true,
    substituto: false,
    horasTrabalhadas: 176,
    riscoInconformidade: "medio",
  },
  {
    id: "func-9",
    fiscalizacaoId: "fis-3",
    nome: "Roberto Nunes",
    cargo: "Auxiliar de Limpeza",
    salario: 1800,
    recebeuVT: true,
    recebeuFGTS: true,
    recebeuINSS: true,
    recebeuCestaBasica: true,
    substituto: true,
    horasTrabalhadas: 88,
    riscoInconformidade: "medio",
  },
]
